Repository ReactionMechanismGenerator/RMG-database, pull requests merged in 2018-06, with the labels that each got.

#271 Reorganization of Intra_R_Add_Endocyclic/Exocyclic and training reactions
  input/kinetics/families/Intra_2+2_cycloaddition_Cd/groups.py
  input/kinetics/families/Intra_Diels_alder_monocyclic/groups.py
  input/kinetics/families/Intra_R_Add_Endocyclic/groups.py
  input/kinetics/families/Intra_R_Add_Endocyclic/training/dictionary.txt
  input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
  input/kinetics/families/Intra_R_Add_Exocyclic/groups.py
  input/kinetics/families/Intra_R_Add_Exocyclic/training/dictionary.txt
  input/kinetics/families/Intra_R_Add_Exocyclic/training/reactions.py
Labels: Status: Review Needed

#278 Change order of unit tests for travis build
  .travis.yml
Labels: Complexity: Low, Status: Review Needed

#272 Added training reactions found to be important in rich-methane modeling
  input/kinetics/families/H_Abstraction/training/dictionary.txt
  input/kinetics/families/H_Abstraction/training/reactions.py
  input/kinetics/families/Intra_R_Add_Endocyclic/training/dictionary.txt
  input/kinetics/families/Intra_R_Add_Endocyclic/training/reactions.py
  input/kinetics/families/Intra_ene_reaction/training/dictionary.txt
  input/kinetics/families/Intra_ene_reaction/training/reactions.py
  input/kinetics/families/R_Addition_COm/training/dictionary.txt
  input/kinetics/families/R_Addition_COm/training/reactions.py
  input/kinetics/families/R_Addition_MultipleBond/training/dictionary.txt
  input/kinetics/families/R_Addition_MultipleBond/training/reactions.py
  input/kinetics/families/R_Recombination/training/dictionary.txt
  input/kinetics/families/R_Recombination/training/reactions.py
  input/kinetics/families/intra_H_migration/training/dictionary.txt
  input/kinetics/families/intra_H_migration/training/reactions.py
Labels: Status: Accepted, Topic: Kinetics

#282 Clean up global forbidden structures
  input/forbiddenStructures.py
Labels: Complexity: Low, Status: Review Needed

#283 Remove old convertKineticsLibraryToTrainingReactions script
  scripts/convertKineticsLibraryToTrainingReactions.ipynb
Labels: Complexity: Low, Status: Review Needed
