Repository ReactionMechanismGenerator/RMG-database, pull requests merged in 2018-05, with the labels that each got.

#265 Corrected s^-1 units in N_D&B kinetic family
  input/kinetics/libraries/Nitrogen_Dean_and_Bozzelli/reactions.py
Labels: PR Ready for Review, PR Small

#267 Remove gauche.py and int15.py
  input/thermo/groups/gauche.py
  input/thermo/groups/int15.py
Labels: PR Ready to Merge, PR Small

#201 Fixes the longDesc attribute of two nodes that were improperly changed
  input/kinetics/families/H_Abstraction/rules.py
Labels: PR Ready for Review, PR Small

#261 Added H_Abstraction and CO_Disprop training reactions
  input/kinetics/families/CO_Disproportionation/training/dictionary.txt
  input/kinetics/families/CO_Disproportionation/training/reactions.py
  input/kinetics/families/H_Abstraction/training/dictionary.txt
  input/kinetics/families/H_Abstraction/training/reactions.py
Labels: Kinetics, PR Ready to Merge

#270 Merge v2.1.9 updates
  meta.yaml
  setup.py
Labels: PR Ready for Review, PR Small

#264 Add CO and CS to ene group in Diels_alder_addition
  input/kinetics/families/Diels_alder_addition/groups.py
Labels: PR Ready for Review, PR Small

#268 Modify the recipe for R_Addition_COm to make it reasonable
  input/kinetics/families/R_Addition_COm/groups.py
Labels: Twin RMG-Py PR
