Repository ReactionMechanismGenerator/RMG-database, pull requests merged in 2020-05, with the labels that each got.

#403 Add data for AEC, BAC, and frequency scale factors
  input/quantum_corrections/data.py
Labels: Complexity: Low, Status: Review Needed, Twin RMG-Py PR

#406 Fix species information for select reference species
  input/reference_sets/main/Benzylide.yml
  input/reference_sets/main/Ethynol anion.yml
  input/reference_sets/main/Formyl anion.yml
  input/reference_sets/main/Methanide.yml
  input/reference_sets/main/Vinoxide.yml
  input/reference_sets/main/Vinyl anion.yml
Labels: Status: Review Needed

#401 Added a rate rule in 2+2_cycloaddition_Cd/rules.py
  input/kinetics/families/2+2_cycloaddition_Cd/rules.py
Labels: Complexity: Low, Status: Review Needed

#408 Fix species information errors for species 151 and 61
  input/reference_sets/main/12-Propadienyl anion.yml
  input/reference_sets/main/2-Propynylidyne.yml
  input/reference_sets/main/Chloromethylene.yml
  input/reference_sets/main/Dichloromethylene.yml
  input/reference_sets/main/Difluoromethylene.yml
  input/reference_sets/main/Ethylidyne.yml
  input/reference_sets/main/Fluoromethylene.yml
  input/reference_sets/main/Fluoromethylidyne.yml
  input/reference_sets/main/Formaldehyde cation.yml
  input/reference_sets/main/Hydroxymethylene.yml
  input/reference_sets/main/Propadienylidene.yml
  input/reference_sets/main/Vinylidene.yml
Labels: Complexity: Low, Status: Review Needed, Type: Error

#415 Atom energy fitting
  input/quantum_corrections/data.py
  input/reference_sets/main/Ammonia.yml
  input/reference_sets/main/Chloromethane.yml
  input/reference_sets/main/Dibromine.yml
  input/reference_sets/main/Dichlorine.yml
  input/reference_sets/main/Difluorine.yml
  input/reference_sets/main/Dihydrogen.yml
  input/reference_sets/main/Dinitrogen.yml
  input/reference_sets/main/Dioxygen.yml
  input/reference_sets/main/Disulfur.yml
  input/reference_sets/main/Hydrogen bromide.yml
  input/reference_sets/main/Hydrogen chloride.yml
  input/reference_sets/main/Hydrogen fluoride.yml
  input/reference_sets/main/Hydrogen sulfide.yml
  input/reference_sets/main/Methane.yml
  input/reference_sets/main/Methyl.yml
  input/reference_sets/main/Water.yml
Labels: Status: Discussion Needed, Twin RMG-Py PR

#420 Fix ref load
  input/reference_sets/main/12-Propadienyl anion.yml
  input/reference_sets/main/Benzylide.yml
  input/reference_sets/main/Chloromethane.yml
  input/reference_sets/main/Dichlorine.yml
  input/reference_sets/main/Hydrogen sulfide.yml
  input/reference_sets/main/Hydroxylamine.yml
  input/reference_sets/main/Methyl.yml
  input/reference_sets/main/Vinyl anion.yml
  input/reference_sets/main/Water.yml
Labels: Complexity: Low
