Repository ReactionMechanismGenerator/RMG-database, pull requests merged in 2021-11, with the labels that each got.

#542 `XY_elimination_hydroxyl` family
  families/images/XY_elimination_hydroxyl.png
  families/rmg_reaction_families.pdf
  input/kinetics/families/XY_elimination_hydroxyl/groups.py
  input/kinetics/families/XY_elimination_hydroxyl/rules.py
  input/kinetics/families/XY_elimination_hydroxyl/template.cdx
  input/kinetics/families/XY_elimination_hydroxyl/template.eps
  input/kinetics/families/XY_elimination_hydroxyl/training/dictionary.txt
  input/kinetics/families/XY_elimination_hydroxyl/training/reactions.py
  input/kinetics/families/recommended.py
Labels: Topic: Kinetics, Topic: Halogens

#545 Bimolec hydroperoxide decomposition
  input/kinetics/families/Bimolec_Hydroperoxide_Decomposition/groups.py
  input/kinetics/families/Bimolec_Hydroperoxide_Decomposition/rules.py
  input/kinetics/families/Bimolec_Hydroperoxide_Decomposition/training/dictionary.txt
  input/kinetics/families/Bimolec_Hydroperoxide_Decomposition/training/reactions.py
Labels: Twin RMG-Py PR, Type: Error

#546 Intra halogen migration family
  families/images/intra_halogen_migration.png
  families/rmg_reaction_families.pdf
  input/kinetics/families/intra_halogen_migration/groups.py
  input/kinetics/families/intra_halogen_migration/rules.py
  input/kinetics/families/intra_halogen_migration/template.cdx
  input/kinetics/families/intra_halogen_migration/template.eps
  input/kinetics/families/intra_halogen_migration/training/dictionary.txt
  input/kinetics/families/intra_halogen_migration/training/reactions.py
  input/kinetics/families/recommended.py
Labels: Topic: Halogens

#529 Generated trees for 1,3_NH3_elimination
  input/kinetics/families/1,3_NH3_elimination/groups.py
  input/kinetics/families/1,3_NH3_elimination/rules.py
Labels: Topic: Tree Gen
