Repository ReactionMechanismGenerator/RMG-database, pull requests merged in 2021-07, with the labels that each got.

#489 Fixed enthalpy errors in adsorption corrections for O-containing species on Pt(111)
  input/thermo/groups/adsorptionPt111.py
  input/thermo/libraries/surfaceThermoPt111.py
Labels: Status: Accepted, Topic: Catalysis

#497 Halogens thermo update
  input/thermo/groups/group.py
  input/thermo/groups/longDistanceInteraction_cyclic.py
  input/thermo/groups/longDistanceInteraction_noncyclic.py
  input/thermo/groups/radical.py
  input/thermo/groups/ring.py
Labels: Status: Accepted, Topic: Thermo, halogens

#482 Fix the number of unpaired radicals in surface vdW families.
  input/kinetics/families/Surface_Abstraction_Single_vdW/groups.py
  input/kinetics/families/Surface_Abstraction_vdW/groups.py
  input/kinetics/families/Surface_Addition_Single_vdW/groups.py
  input/kinetics/families/Surface_Adsorption_Abstraction_vdW/groups.py
  input/kinetics/families/Surface_Dissociation_Double_vdW/groups.py
  input/kinetics/families/Surface_Dissociation_vdW/groups.py
  input/kinetics/families/Surface_Dual_Adsorption_vdW/groups.py
Labels: Status: Accepted, Topic: Catalysis

#504 Surface training reactions fixups
  input/kinetics/families/Surface_Abstraction_vdW/training/reactions.py
  input/kinetics/families/Surface_Addition_Single_vdW/training/reactions.py
  input/kinetics/families/Surface_Adsorption_Abstraction_vdW/training/reactions.py
  input/kinetics/families/Surface_Adsorption_Dissociative/training/reactions.py
  input/kinetics/families/Surface_Dissociation/training/reactions.py
  input/kinetics/families/Surface_Dissociation_Beta/training/reactions.py
  input/kinetics/families/Surface_Dissociation_Double_vdW/training/reactions.py
  input/kinetics/families/Surface_Dissociation_vdW/training/reactions.py
  input/kinetics/families/Surface_Migration/training/reactions.py
Labels: Status: WIP, Topic: Catalysis

#507 Adding more nodes in some kinetics families tree
  input/kinetics/families/Surface_Adsorption_Double/groups.py
  input/kinetics/families/Surface_Adsorption_Single/groups.py
  input/kinetics/families/Surface_Adsorption_vdW/groups.py
  input/kinetics/families/Surface_Dissociation/groups.py
  input/kinetics/families/Surface_Dissociation_Beta/groups.py
Labels: Status: Accepted, Topic: Catalysis

#505 Fixed minor error in the solvent library
  input/solvation/libraries/solvent.py
Labels: Complexity: Low

#462 Coverage dependence of kinetics
  input/kinetics/libraries/Surface/CPOX_Pt/Deutschmann2006/reactions.py
  input/kinetics/libraries/Surface/CPOX_Pt/Deutschmann2006_adjusted/dictionary.txt
  input/kinetics/libraries/Surface/CPOX_Pt/Deutschmann2006_adjusted/reactions.py
Labels: Topic: Catalysis, Twin RMG-Py PR

#506 Adding surface libraries
  input/kinetics/libraries/Surface/Ammonia/Duan_Ni111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Duan_Ni111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Duan_Ni211/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Duan_Ni211/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Kraehnert_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Kraehnert_Pt111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Novell_Pd111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Novell_Pd111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Novell_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Novell_Pt111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Novell_Rh111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Novell_Rh111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Offermans_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Offermans_Pt111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Popa_Rh111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Popa_Rh111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Rebrov_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Rebrov_Pt111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Roldan_Ru0001/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Roldan_Ru0001/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Scheuer_Pt/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Scheuer_Pt/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pd111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pd111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pd211/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pd211/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pt111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pt211/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Schneider_Pt211/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Schneider_Rh111/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Schneider_Rh111/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Schneider_Rh211/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Schneider_Rh211/reactions.py
  input/kinetics/libraries/Surface/Ammonia/Vlachos_Ru0001/dictionary.txt
  input/kinetics/libraries/Surface/Ammonia/Vlachos_Ru0001/reactions.py
  input/kinetics/libraries/Surface/DOC/Arevalo_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/DOC/Arevalo_Pt111/reactions.py
  input/kinetics/libraries/Surface/DOC/Ishikawa_Rh111/dictionary.txt
  input/kinetics/libraries/Surface/DOC/Ishikawa_Rh111/reactions.py
  input/kinetics/libraries/Surface/DOC/Mhadeshwar_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/DOC/Mhadeshwar_Pt111/reactions.py
  input/kinetics/libraries/Surface/DOC/Nitrogen/dictionary.txt
  input/kinetics/libraries/Surface/DOC/Nitrogen/reactions.py
  input/kinetics/libraries/Surface/Hydrazine/Roldan_Cu111/dictionary.txt
  input/kinetics/libraries/Surface/Hydrazine/Roldan_Cu111/reactions.py
  input/kinetics/libraries/Surface/Hydrazine/Roldan_Ir111/dictionary.txt
  input/kinetics/libraries/Surface/Hydrazine/Roldan_Ir111/reactions.py
  input/kinetics/libraries/Surface/Methane/Deutschmann_Ni/dictionary.txt
  input/kinetics/libraries/Surface/Methane/Deutschmann_Ni/reactions.py
  input/kinetics/libraries/Surface/Methane/Deutschmann_Ni_full/dictionary.txt
  input/kinetics/libraries/Surface/Methane/Deutschmann_Ni_full/reactions.py
  input/kinetics/libraries/Surface/Methane/Deutschmann_Pt/dictionary.txt
  input/kinetics/libraries/Surface/Methane/Deutschmann_Pt/reactions.py
  input/kinetics/libraries/Surface/Methane/Vlachos_Pt111/dictionary.txt
  input/kinetics/libraries/Surface/Methane/Vlachos_Pt111/reactions.py
  input/kinetics/libraries/Surface/Methane/Vlachos_Rh/dictionary.txt
  input/kinetics/libraries/Surface/Methane/Vlachos_Rh/reactions.py
  input/kinetics/libraries/Surface/Nitrogen/dictionary.txt
  input/kinetics/libraries/Surface/Nitrogen/reactions.py
Labels: Topic: Catalysis, Topic: Nitrogen
