Repository ReactionMechanismGenerator/RMG-database, pull requests merged in 2024-03, with the labels that each got.

#596 Update and add BEP rules for surface families
  families/rmg_reaction_families.pdf
  input/kinetics/families/Surface_Abstraction/groups.py
  input/kinetics/families/Surface_Abstraction/rules.py
  input/kinetics/families/Surface_Abstraction_Beta/groups.py
  input/kinetics/families/Surface_Abstraction_Beta/rules.py
  input/kinetics/families/Surface_Abstraction_Beta_double_vdW/groups.py
  input/kinetics/families/Surface_Abstraction_Beta_double_vdW/rules.py
  input/kinetics/families/Surface_Adsorption_Dissociative/groups.py
  input/kinetics/families/Surface_Adsorption_Dissociative/rules.py
  input/kinetics/families/Surface_Dissociation/groups.py
  input/kinetics/families/Surface_Dissociation/rules.py
  input/kinetics/families/Surface_Dissociation_vdW/groups.py
  input/kinetics/families/Surface_Dissociation_vdW/rules.py
  input/kinetics/families/Surface_Dual_Adsorption_vdW/groups.py
  input/kinetics/families/Surface_Dual_Adsorption_vdW/rules.py
  input/kinetics/families/Surface_Dual_Adsorption_vdW/template.cdx
  input/kinetics/families/Surface_Dual_Adsorption_vdW/template.eps
  input/kinetics/families/Surface_Dual_Adsorption_vdW/training/dictionary.txt
  input/kinetics/families/Surface_Dual_Adsorption_vdW/training/reactions.py
  input/kinetics/families/recommended.py
Labels: Topic: Catalysis

#633 fix Surface_Abstraction training reactions format
  input/kinetics/families/Surface_Abstraction/training/dictionary.txt
  input/kinetics/families/Surface_Abstraction/training/reactions.py
Labels: Complexity: Low, Topic: Catalysis

#629 update adsorption corrections
  input/thermo/groups/adsorptionPt111.py
Labels: Complexity: Low, Topic: Thermo, Topic: Catalysis

#628 Update list of default surface reaction families and restrict Abstraction_Single_vdW
  input/kinetics/families/Surface_Abstraction_Single_vdW/groups.py
  input/kinetics/families/Surface_Abstraction_Single_vdW/rules.py
  input/kinetics/families/Surface_Abstraction_vdW/rules.py
  input/kinetics/families/recommended.py
Labels: Complexity: Low, Topic: Catalysis
